### ISSUE TITLE
In the latest release of RealPlume for RO, the plumes look all flat and nasty

### ISSUE THREAD

**Issue by raydkent86** [KSP-RO/RealPlume#1]
The newest version of RealPlume for 1.0.4 has a major issue, namely the problem of the engine plume being too small and not extending downward, looking VERY ugly to the point where my game is unplayable because of the sheer nastiness of the flame. Please help because I can't use RO until this is fixed. Keep in mind that I DO have OpenGL, which may make some difference, but not likely.

**Comment by Felger** [comment]
[Known issue, update SmokeScreen](http://forum.kerbalspaceprogram.com/threads/71630-1-0-SmokeScreen-2-6-6-Extended-FX-plugin-%28July-8th%29?p=2065904&viewfull=1#post2065904)

**Comment by Felger** [comment]
Resolved with the latest smokescreen closing issue.
