### ISSUE TITLE
smokeless plumes

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealPlume#17]
In working on lander engines, I find that any plume that outputs smoke causes the frame rate to drop and the view to be obscured of both the craft and the ground.

Would it be possible to have a toggle option in template plume definitions that allow the smoke to be entirely disabled? I tried a few things to try to remove it after the fact, to no avail. A trick probably exists, but given that a use case exists, it would be handy to have this as an easy toggle.

One failure example of mine: 
    %EFFECTS
    {
        %Ammonialox
        {
            !MODEL_MULTI_PARTICLE_PERSIST[smoke] {}
        }

```
}
```

**Comment by Nhawks1717** [comment]
Closing this. Smoke can be removed by using this code
```javascript
@PART[PartName]:HAS[@PLUME[PlumeName]]:FOR[zzRealPlume]`
{
    @EFFECTS
    {
        @PlumeName
        {
            !MODEL_MULTI_SHURIKEN_PERSIST[smoke] {}
        }
    }
}
```
Make sure you replace the areas with PartName and PlumeName
