### ISSUE TITLE
Feedback on v10.5

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RealPlume#19]
The stock reconfigured Merlin engines produce a bright white ball around 20-30km; I'm not sure if this is intentional, or a result of clustering 2 or 3 together. Above and below that it looks really good. I'm not sure how perpendicular the effect should be to the engine at high altitudes; I would personally expect it to be less perpendicular/pancake shaped than it is at high altitude as exhaust gas thrown backwards is what generates the thrust.

The RL10 effect looks like smoke or hypergolic, not sure if this is a change to RealPlume or KSP 1.1

**Comment by Felger** [comment]
Should be better now.  Feel free to comment again if needs more fixing.

**Comment by stratochief66** [comment]
@Felger 

Both under 1.0.5 and 1.1, I am seeing the plumes incorrectly placed to high (sometimes starting above/ahead of the whole craft) for hypergolic plumes.

Edit: Hypergolic-Uppers, specifically. I haven't seen any problem with lower stages.
