### ISSUE TITLE
Compatibility with secondary exhaust port effects

### ISSUE THREAD

**Issue by blowfishpro** [KSP-RO/RealPlume#20]
Now that KSP 1.1 supports varying thrust per transform, people are moving vernier/exhaust thrust onto the main engine module, but this seems to not play well with the way RealPlume works
- If you try to give the main and verniers the same plume, RealPlume will only read from the first `PLUME` node and whatever is in the second will be completely ignored
- If you try to give them different plumes, RealPlume puts them into separate effect nodes.  This can work if you give one to `powerEffectName` and one to some other effect type on the engine, but I don't think the plumes are intended to be used with anything other than power (thrust/max thrust).

**Comment by PhineasFreak** [comment]
Although this is an old issue, i just came across it when updating the DECQ R-7 (cannot assign two Kerolox-Vernier nodes for two different thrust transforms in the same part).

RealPlume patches the particle generator by MM inserting them via the "%"  modifier. Example:

https://github.com/KSP-RO/RealPlume/blob/master/GameData/RealPlume/000_Generic_Plumes/Hypergolic-Vernier.cfg#L5

This will of course fail if you have already included a plume definition with the same name, as it will patch the existing one. Maybe inserting them directly (by removing the "%" modifier from the name) will fix this, as it will add any following plume patches after the first one.

**Comment by blowfishpro** [comment]
This should now be possible in #42, though the `*-Vernier` plumes have largely solved this issue on their own
