### ISSUE TITLE
Logspam FloatCurve: Invalid line

### ISSUE THREAD

**Issue by jsolson** [KSP-RO/RealPlume#22]
[Line 208](https://github.com/KSP-RO/RealPlume/blob/master/GameData/RealPlume/000_Generic_Plumes/Kerolox-Lower.cfg#L208) of the generic plume Kerolox-Lower is missing a value.

It's producing "FloatCurve: Invalid line. Requires two values, 'time' and 'value'" errors on every engine that uses it.

**Comment by lOmicronl** [comment]
Same problem in line 216 of Kerolox-Upper.cfg. Also missing a value, also popping that error repeatedly.

**Comment by PhineasFreak** [comment]
Additional plumes that show the same float curve errors:

* Hypergolic-OMS-White
* Ion-Xenon-Hall
* Turbofan

**Comment by Nhawks1717** [comment]
Fixed in [v11.0.0](https://github.com/KSP-RO/RealPlume/releases/latest)

**Comment by yalov** [comment]
Is it RP error? I have plenty of those:

Squad: ionEngine, turboJet, JetEngine, turboFanSize2, turboFanEngine, liquidEngineMini, radialEngineMini, liquidEngine3, liquidEngine2-2, miniJetEngine, omsEngine, RAPIER

MakingHistory: LiquidEngineLV-T91, LiquidEngineRE-J10, MEMLander

ModRocketSys: NB0mMonoEngine1, NB3mHoundEngine
SXT: SXTVTOLturboFan, SXTMiniJet, SXTKOPO4E
VenStockRevamp: liquidEngineMiniTurbo, size0PulseJet
NearFuturePropulsion: ionArgon-0625-2, ionArgon-0625-3, ionArgon-0625, pit-0625, pit-125, pit-25, vasimr-0625, vasimr-125, vasimr-25
