### ISSUE TITLE
RealPlume removes entire EFFECTS block even when other effects are using it.

### ISSUE THREAD

**Issue by shadowmage45** [KSP-RO/RealPlume#24]
From: https://github.com/KSP-RO/RealPlume/blob/master/GameData/RealPlume/000_Generic_Plumes/000_EFFECTS_Remover.cfg

This results in the deletion of the entire EFFECTS block whenever a RealPlumes config is detected for a part.  This causes problems with parts that have other non-RP effects in use -- for example decouplers with integrated separation engines, or engine and RCS equipped parts that also use the ModuleRCSFX setup for their effects.

Current work-around is to re-declare the deleted EFFECTS for the non-realplume effects on a part in a FINAL block -- however this creates a large amount of overhead to adding RealPlumes to many parts, especially on parts with complex effects setups.

Example of current workaround, to fix missing decoupler sounds after real-plumes is added to the decouplers for separation motors: https://github.com/shadowmage45/SSTULabs/blob/master/GameData/SSTU/Patches/RealPlumes-ShipCore.cfg#L228-L232

**Comment by Nhawks1717** [comment]
Fixed in [v11.0.0](https://github.com/KSP-RO/RealPlume/releases/latest)
