### ISSUE TITLE
Making a release?

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RealPlume#30]
@PhineasFreak @Nhawks1717  you folks had outstanding PRs I saw no reason not to merge. We should probably make a release, too...

**Comment by Nhawks1717** [comment]
Updated release sounds good to me!

**Comment by PhineasFreak** [comment]
Yay! I fully agree.

@Nhawks1717 i love the fact that you added the smoke patch. There are literally a ton of RealPlume configs that needed AFTER passes to make the smoke work, adding a large MM overhead. But not anymore!

**Edit 1:** should we update the "Adding a Plume to an Engine" wiki page?

**Edit 2:** we also have minor problems with the curves missing some fields: https://github.com/KSP-RO/RealPlume/issues/22. Should we also tackle it before the new release?

**Comment by PhineasFreak** [comment]
I have made some updates to the "Adding a Plume to an Engine" wiki page. Hope that you like them!

**Comment by Nhawks1717** [comment]
So I'm just now noticing that for SRB plumes the "slag" definitions don't bind to any change in scale which is presenting a problem for me updating the FASA configs.... Thoughts on me changing SRB plumes to use this instead?
```javascript
MODEL_MULTI_SHURIKEN_PERSIST
            {
                //Get the inputs from the other config.
                transformName = #$../../../PLUME[Solid-Lower]/transformName$
                localRotation = #$../../../PLUME[Solid-Lower]/localRotation[0]$,$../../../PLUME[Solid-Lower]/localRotation[1]$,$../../../PLUME[Solid-Lower]/localRotation[2]$
                localPosition = #$../../../PLUME[Solid-Lower]/plumePosition[0]$,$../../../PLUME[Solid-Lower]/plumePosition[1]$,$../../../PLUME[Solid-Lower]/plumePosition[2]$
                fixedScale    = #$../../../PLUME[Solid-Lower]/plumeScale$
                //
                name = slag
```
All it's doing is binding slag scale size to the plumeScale definition

**Comment by PhineasFreak** [comment]
Or even make it semi-independent, like the new smokeScale parameter? I also had this problem with some solids and i wish i had the way to manage them without AFTER passes.

**Comment by Nhawks1717** [comment]
I was thinking that too, just didn't know if it was necessarily needed but that would work! I'll submit a pull request for it later today...

**Comment by Nhawks1717** [comment]
PR is open. Feel free to look over it and merge it if you think it looks good :)

**Comment by NathanKell** [comment]
You guys should both have admin privileges here and for stockconfigs now, so you can push/merge/release yourselves :)

**Comment by Nhawks1717** [comment]
New release is done ;)
