### ISSUE TITLE
Game freezes for some time, sometimes

### ISSUE THREAD

**Issue by BTAxis** [KSP-RO/RealPlume#67]
My experience with Real Plume has been that from time to time, the game will freeze for a while, maybe 30 seconds at a time. It becomes unresponsive during this time, but it will always come out of it. Once it does, the game runs perfectly fine again.

This situation triggers either when
1) I launch a rocket, or
2) When a craft passes below 70Km over Kerbin.

But, not always. Repeating the same launch with the same craft in the same circumstances sometimes works fine, sometimes it freezes.

Removal of Real Plume has completely eliminated this behavior.

**Comment by zorg2044** [comment]
Hmm do you have a log file for this? Although I have to say usually if its not a module manager error such problems are Smokescreen related rather than directly to do with realplume (realplume is just a set of MM configs).

Which version of smokescreen do you have installed?

**Comment by BTAxis** [comment]
I'm unsure which log is relevant here, there seem to be several scattered about. It's also hard to reproduce reliably, as I've said, so producing a clean log might be problematic.

I got Real Plume (and by extension Smokescreen) via CKAN, so it's version 2.8.6.0.

**Comment by zorg2044** [comment]
The most relevant one would be the output log. Its not anywhere in your game data, you can check this forum post on where to get it based on your OS and game version.

https://forum.kerbalspaceprogram.com/index.php?/topic/163863-how-to-get-support/

Best thing would be to quit the game as soon as its happened and then grab the log (if you can reproduce it). I can take a look if you can do this but as mentioned I think whatever it is would likely be related to smokescreen in which case you would need to follow up with the smokescreen dev.

**Comment by BTAxis** [comment]
I can't seem to reproduce this at all anymore, but I do suspect that my issue was related to a broken install of the mod, because my plumes appear different than before. The plume coming out of a basic booster appears grey, whereas before it was black.

I didn't do anything different this time though, I just told CKAN to install and let it auto-install the dependencies.

Oh well. Closing this now.
