### ISSUE TITLE
[Deleted]

### ISSUE THREAD

**Issue by Chandra-Aerospace** [KSP-RO/RealPlume#77]
The Hydolox_lowerBlaze has a fumeScale and fumePosition, but does not show any particles.

**Comment by zorg2044** [comment]
![Screenshot 2019-10-29 11 57 04](https://user-images.githubusercontent.com/39182212/67744459-5f4ac800-fa43-11e9-802f-d27b2296c433.png)

seems to be working for me? Its meant to be invisible and only starts fading in from a density of 0.19 onwards. This is on a clean install and I dont see any errors in the file path names either.

**Comment by Chandra-Aerospace** [comment]
Just discovered that.
Heck, I was going to delete this but you beat me too it 😂
