### ISSUE TITLE
[Enhancement] add Supersonic Smoke plume to Cryogenic_Albative_CE

### ISSUE THREAD

**Issue by Chandra-Aerospace** [KSP-RO/RealPlume#78]
Very related to the request for Kerolox Black smoke, It would be amazing if you could add supersonic smoke to the Cryogenic_Albative_CE plume!

**Comment by zorg2044** [comment]
It is in fact possible to add an effect based on mach speed so a genuine transonic effect is possible. I'll put this on the "to consider" list. Its not a high priority but could be an interesting enhancement for many booster plumes if it can be done nicely.

A trailing effect would be quite hard but would be more effective but a regular effect may work if that proves too difficult. Will have to look at this at a later date though.
