### ISSUE TITLE
Disappearing plume model in KSP 1.8

### ISSUE THREAD

**Issue by zorg2044** [KSP-RO/RealPlume#80]
``hypergolicVernierOrange_stream`` does not seem to load in KSP 1.8 although it does in KSP 1.7.3, cause unknown at present.

**Comment by ioulaum-c** [comment]
For me, it happens only when using together with Ven's Stock Part Revamp.

**Comment by zorg2044** [comment]
https://github.com/KSP-RO/RealPlume/commit/d73d443aacedb2a907dca0c30133321096e1ab6a

Caused by incorrect shader on material. Fixed with https://github.com/KSP-RO/RealPlume/commit/d73d443aacedb2a907dca0c30133321096e1ab6a
