### ISSUE TITLE
Issue with the new Hydynelox

### ISSUE THREAD

**Issue by lukecologne** [KSP-RO/RealPlume#84]
It seems like the new Hydynelox plume is missing a texture: 
![screenshot25](https://user-images.githubusercontent.com/39596827/78504418-694cc180-776d-11ea-8520-4ea9a3a0d49c.png)
The particles are coming from the Hydynelox-core effect.
I did a fresh install of RealPlume to see if that would fix it, but no luck.

**Comment by zorg2044** [comment]
I'll try and get a fix up soon along with some other updates.

**Comment by zorg2044** [comment]
Should be fixed now 42e91cda3cb9ae79365055eb3f2abd76508a784a

![image](https://user-images.githubusercontent.com/39182212/79064934-50d92b80-7cc6-11ea-9894-417c4130afc6.png)
