### ISSUE TITLE
AtomicAge, FTMN & FTMN_New

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-RO/RealPlume#86]
Was wondering if any of you kind souls would care to make up a set of configs for the engines in the above mods (FTMN & FTMN_new are really one mod in two directories)

If interested, both those mods are now contained inside my RecycledParts mod, available on Github here:

https://github.com/linuxgurugamer/RecycledParts

Thanks

**Comment by zorg2044** [comment]
All of these nuclear engines are already covered in RealPlume-Stock configs I believe.

https://github.com/KSP-RO/RealPlume-StockConfigs/tree/master/GameData/RealPlume-Stock/SpaceTuxIndustries_RecycledParts/AtomicAge

https://github.com/KSP-RO/RealPlume-StockConfigs/tree/master/GameData/RealPlume-Stock/FTmN_Atomic_Rockets

**Comment by linuxgurugamer** [comment]
Ah. Ok thank you
