### ISSUE TITLE
RD-109 engine has a plume far behind the engine

### ISSUE THREAD

**Issue by aaronstatic** [KSP-RO/RealPlume#88]
When using the RD-109/119 engine there is a part of the plume positioned about 1km behind the craft
![image](https://user-images.githubusercontent.com/899639/82812688-e4f9fd80-9ed6-11ea-92c9-0e09e0446f6f.png)

**Comment by zorg2044** [comment]
What mod? If this is RO this needs to be reported to the RO repository directly. RealPlume is just the plume presets. no engine configs here.

**Comment by aaronstatic** [comment]
sorry my bad.. this seems to be fixed in ROEngines master anyway, will close
