### ISSUE TITLE
Plume from VASIMR comes out of the wrong place

### ISSUE THREAD

**Issue by georgedorn** [KSP-RO/RealPlume#91]
Instead of coming from the nozzle, the plume seems to be emitting from the nuclear reactor.

I'm on 1.9.1 because Kopernicus isn't quite ready for 1.10.  This happens with every gas I've tested; liquid xenon, liquid argon, liquid hydrogen, liquid neon.  Perhaps RealPlume is expecting non-liquid versions of the gasses?

![20200716124005_1](https://user-images.githubusercontent.com/239067/87715042-942db500-c761-11ea-993e-ed6384b5e482.jpg)

**Comment by georgedorn** [comment]
Additional test:  I replaced the scaled parts with original-sized FLAT reactor and VASIMIR and got a slightly different result:
![20200716134539_1](https://user-images.githubusercontent.com/239067/87721039-b37d1000-c76a-11ea-8806-4ab29a14deb1.jpg)

The plume shifted with the rescaling, so it's not actually coming from the reactor.  Instead, it seems to just be coming from several meters above the nozzle.

**Comment by georgedorn** [comment]
[interstellar_1.9.txt](https://github.com/KSP-RO/RealPlume/files/4934087/interstellar_1.9.txt)
Here's my mod list and a recent log.
[KSP - Copy.log](https://github.com/KSP-RO/RealPlume/files/4934091/KSP.-.Copy.log)

**Comment by zorg2044** [comment]
@georgedorn the Vasimir engine from which mod? if its KSPIE those configs are in that mod, not in RealPlume or RealPlume stock
